apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: ghcr.io/gmtstephane/kpture_proxy:latest
          imagePullPolicy: Always
          resources:
