FROM golang:1.19-alpine as base


RUN apk update
RUN apk add build-base
COPY . /app/service
WORKDIR /app/service
# Build the Go app
RUN go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" -o /app/service/kpture cmd/proxy/main.go

FROM scratch
# Copy our static executable.
COPY --from=base /app/service/kpture /kpture
CMD ["/kpture"]