FROM golang:1.19-alpine as base

RUN apk update
RUN apk add build-base libpcap-dev libpcap
COPY . /app/service
WORKDIR /app/service
RUN go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" -o /app/service/kpture cmd/agent/main.go

FROM scratch
# Copy our static executable.
COPY --from=base /app/service/kpture /kpture

CMD ["/kpture"]