# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kpture < Formula
  desc "kubernetes packet capture tool"
  homepage "https://github.com/gmtstephane/kpture"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.10/kpture_Darwin_arm64.tar.gz"
      sha256 "3c3f499a67e3e7337e92a15514cc1596e62dfa4cbbc8ea72edd049a32f3a6b16"

      def install
        bin.install "kpture"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.10/kpture_Darwin_x86_64.tar.gz"
      sha256 "00514838a3cead4618706784606f26da795f45b822607d89fd90b0e352026e39"

      def install
        bin.install "kpture"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.10/kpture_Linux_x86_64.tar.gz"
      sha256 "9060a6e519b988cd07f5be1fef5ae85ed0f32f3f86883dc519427b221b8ad800"

      def install
        bin.install "kpture"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmtstephane/kpture/releases/download/v0.0.10/kpture_Linux_arm64.tar.gz"
      sha256 "a7d8d3ea1270ab25d4449d16d2cb5835a40cf1fc20fc5eee8d5e9819577944d7"

      def install
        bin.install "kpture"
      end
    end
  end
end
