// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/capture/capture_grpc.pb.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	capture "github.com/gmtstephane/kpture/api/capture"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockKptureClient is a mock of KptureClient interface.
type MockKptureClient struct {
	ctrl     *gomock.Controller
	recorder *MockKptureClientMockRecorder
}

// MockKptureClientMockRecorder is the mock recorder for MockKptureClient.
type MockKptureClientMockRecorder struct {
	mock *MockKptureClient
}

// NewMockKptureClient creates a new mock instance.
func NewMockKptureClient(ctrl *gomock.Controller) *MockKptureClient {
	mock := &MockKptureClient{ctrl: ctrl}
	mock.recorder = &MockKptureClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKptureClient) EXPECT() *MockKptureClientMockRecorder {
	return m.recorder
}

// PacketsStream mocks base method.
func (m *MockKptureClient) PacketsStream(ctx context.Context, in *capture.Empty, opts ...grpc.CallOption) (capture.Kpture_PacketsStreamClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PacketsStream", varargs...)
	ret0, _ := ret[0].(capture.Kpture_PacketsStreamClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PacketsStream indicates an expected call of PacketsStream.
func (mr *MockKptureClientMockRecorder) PacketsStream(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PacketsStream", reflect.TypeOf((*MockKptureClient)(nil).PacketsStream), varargs...)
}

// MockKpture_PacketsStreamClient is a mock of Kpture_PacketsStreamClient interface.
type MockKpture_PacketsStreamClient struct {
	ctrl     *gomock.Controller
	recorder *MockKpture_PacketsStreamClientMockRecorder
}

// MockKpture_PacketsStreamClientMockRecorder is the mock recorder for MockKpture_PacketsStreamClient.
type MockKpture_PacketsStreamClientMockRecorder struct {
	mock *MockKpture_PacketsStreamClient
}

// NewMockKpture_PacketsStreamClient creates a new mock instance.
func NewMockKpture_PacketsStreamClient(ctrl *gomock.Controller) *MockKpture_PacketsStreamClient {
	mock := &MockKpture_PacketsStreamClient{ctrl: ctrl}
	mock.recorder = &MockKpture_PacketsStreamClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKpture_PacketsStreamClient) EXPECT() *MockKpture_PacketsStreamClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockKpture_PacketsStreamClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockKpture_PacketsStreamClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockKpture_PacketsStreamClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockKpture_PacketsStreamClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockKpture_PacketsStreamClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockKpture_PacketsStreamClient)(nil).Context))
}

// Header mocks base method.
func (m *MockKpture_PacketsStreamClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockKpture_PacketsStreamClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockKpture_PacketsStreamClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockKpture_PacketsStreamClient) Recv() (*capture.Packet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*capture.Packet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockKpture_PacketsStreamClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockKpture_PacketsStreamClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockKpture_PacketsStreamClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockKpture_PacketsStreamClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockKpture_PacketsStreamClient)(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockKpture_PacketsStreamClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockKpture_PacketsStreamClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockKpture_PacketsStreamClient)(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockKpture_PacketsStreamClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockKpture_PacketsStreamClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockKpture_PacketsStreamClient)(nil).Trailer))
}

// MockKptureServer is a mock of KptureServer interface.
type MockKptureServer struct {
	ctrl     *gomock.Controller
	recorder *MockKptureServerMockRecorder
}

// MockKptureServerMockRecorder is the mock recorder for MockKptureServer.
type MockKptureServerMockRecorder struct {
	mock *MockKptureServer
}

// NewMockKptureServer creates a new mock instance.
func NewMockKptureServer(ctrl *gomock.Controller) *MockKptureServer {
	mock := &MockKptureServer{ctrl: ctrl}
	mock.recorder = &MockKptureServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKptureServer) EXPECT() *MockKptureServerMockRecorder {
	return m.recorder
}

// PacketsStream mocks base method.
func (m *MockKptureServer) PacketsStream(arg0 *capture.Empty, arg1 capture.Kpture_PacketsStreamServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PacketsStream", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PacketsStream indicates an expected call of PacketsStream.
func (mr *MockKptureServerMockRecorder) PacketsStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PacketsStream", reflect.TypeOf((*MockKptureServer)(nil).PacketsStream), arg0, arg1)
}

// mustEmbedUnimplementedKptureServer mocks base method.
func (m *MockKptureServer) mustEmbedUnimplementedKptureServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedKptureServer")
}

// mustEmbedUnimplementedKptureServer indicates an expected call of mustEmbedUnimplementedKptureServer.
func (mr *MockKptureServerMockRecorder) mustEmbedUnimplementedKptureServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedKptureServer", reflect.TypeOf((*MockKptureServer)(nil).mustEmbedUnimplementedKptureServer))
}

// MockUnsafeKptureServer is a mock of UnsafeKptureServer interface.
type MockUnsafeKptureServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeKptureServerMockRecorder
}

// MockUnsafeKptureServerMockRecorder is the mock recorder for MockUnsafeKptureServer.
type MockUnsafeKptureServerMockRecorder struct {
	mock *MockUnsafeKptureServer
}

// NewMockUnsafeKptureServer creates a new mock instance.
func NewMockUnsafeKptureServer(ctrl *gomock.Controller) *MockUnsafeKptureServer {
	mock := &MockUnsafeKptureServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeKptureServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeKptureServer) EXPECT() *MockUnsafeKptureServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedKptureServer mocks base method.
func (m *MockUnsafeKptureServer) mustEmbedUnimplementedKptureServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedKptureServer")
}

// mustEmbedUnimplementedKptureServer indicates an expected call of mustEmbedUnimplementedKptureServer.
func (mr *MockUnsafeKptureServerMockRecorder) mustEmbedUnimplementedKptureServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedKptureServer", reflect.TypeOf((*MockUnsafeKptureServer)(nil).mustEmbedUnimplementedKptureServer))
}

// MockKpture_PacketsStreamServer is a mock of Kpture_PacketsStreamServer interface.
type MockKpture_PacketsStreamServer struct {
	ctrl     *gomock.Controller
	recorder *MockKpture_PacketsStreamServerMockRecorder
}

// MockKpture_PacketsStreamServerMockRecorder is the mock recorder for MockKpture_PacketsStreamServer.
type MockKpture_PacketsStreamServerMockRecorder struct {
	mock *MockKpture_PacketsStreamServer
}

// NewMockKpture_PacketsStreamServer creates a new mock instance.
func NewMockKpture_PacketsStreamServer(ctrl *gomock.Controller) *MockKpture_PacketsStreamServer {
	mock := &MockKpture_PacketsStreamServer{ctrl: ctrl}
	mock.recorder = &MockKpture_PacketsStreamServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKpture_PacketsStreamServer) EXPECT() *MockKpture_PacketsStreamServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockKpture_PacketsStreamServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockKpture_PacketsStreamServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockKpture_PacketsStreamServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockKpture_PacketsStreamServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockKpture_PacketsStreamServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockKpture_PacketsStreamServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockKpture_PacketsStreamServer) Send(arg0 *capture.Packet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockKpture_PacketsStreamServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockKpture_PacketsStreamServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockKpture_PacketsStreamServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockKpture_PacketsStreamServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockKpture_PacketsStreamServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockKpture_PacketsStreamServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockKpture_PacketsStreamServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockKpture_PacketsStreamServer)(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockKpture_PacketsStreamServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockKpture_PacketsStreamServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockKpture_PacketsStreamServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockKpture_PacketsStreamServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockKpture_PacketsStreamServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockKpture_PacketsStreamServer)(nil).SetTrailer), arg0)
}
