// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: capture/capture.proto

package capture

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KptureClient is the client API for Kpture service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KptureClient interface {
	PacketsStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Kpture_PacketsStreamClient, error)
}

type kptureClient struct {
	cc grpc.ClientConnInterface
}

func NewKptureClient(cc grpc.ClientConnInterface) KptureClient {
	return &kptureClient{cc}
}

func (c *kptureClient) PacketsStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Kpture_PacketsStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Kpture_ServiceDesc.Streams[0], "/service.Kpture/PacketsStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &kpturePacketsStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kpture_PacketsStreamClient interface {
	Recv() (*Packet, error)
	grpc.ClientStream
}

type kpturePacketsStreamClient struct {
	grpc.ClientStream
}

func (x *kpturePacketsStreamClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KptureServer is the server API for Kpture service.
// All implementations must embed UnimplementedKptureServer
// for forward compatibility
type KptureServer interface {
	PacketsStream(*Empty, Kpture_PacketsStreamServer) error
	mustEmbedUnimplementedKptureServer()
}

// UnimplementedKptureServer must be embedded to have forward compatible implementations.
type UnimplementedKptureServer struct {
}

func (UnimplementedKptureServer) PacketsStream(*Empty, Kpture_PacketsStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method PacketsStream not implemented")
}
func (UnimplementedKptureServer) mustEmbedUnimplementedKptureServer() {}

// UnsafeKptureServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KptureServer will
// result in compilation errors.
type UnsafeKptureServer interface {
	mustEmbedUnimplementedKptureServer()
}

func RegisterKptureServer(s grpc.ServiceRegistrar, srv KptureServer) {
	s.RegisterService(&Kpture_ServiceDesc, srv)
}

func _Kpture_PacketsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KptureServer).PacketsStream(m, &kpturePacketsStreamServer{stream})
}

type Kpture_PacketsStreamServer interface {
	Send(*Packet) error
	grpc.ServerStream
}

type kpturePacketsStreamServer struct {
	grpc.ServerStream
}

func (x *kpturePacketsStreamServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

// Kpture_ServiceDesc is the grpc.ServiceDesc for Kpture service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kpture_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Kpture",
	HandlerType: (*KptureServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PacketsStream",
			Handler:       _Kpture_PacketsStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "capture/capture.proto",
}
