// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package capture

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PacketsReceiverClient is the client API for PacketsReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PacketsReceiverClient interface {
	AddPacket(ctx context.Context, opts ...grpc.CallOption) (PacketsReceiver_AddPacketClient, error)
	Ready(ctx context.Context, in *Pod, opts ...grpc.CallOption) (*Empty, error)
}

type packetsReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewPacketsReceiverClient(cc grpc.ClientConnInterface) PacketsReceiverClient {
	return &packetsReceiverClient{cc}
}

func (c *packetsReceiverClient) AddPacket(ctx context.Context, opts ...grpc.CallOption) (PacketsReceiver_AddPacketClient, error) {
	stream, err := c.cc.NewStream(ctx, &PacketsReceiver_ServiceDesc.Streams[0], "/service.PacketsReceiver/AddPacket", opts...)
	if err != nil {
		return nil, err
	}
	x := &packetsReceiverAddPacketClient{stream}
	return x, nil
}

type PacketsReceiver_AddPacketClient interface {
	Send(*Packet) error
	Recv() (*Empty, error)
	grpc.ClientStream
}

type packetsReceiverAddPacketClient struct {
	grpc.ClientStream
}

func (x *packetsReceiverAddPacketClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *packetsReceiverAddPacketClient) Recv() (*Empty, error) {
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *packetsReceiverClient) Ready(ctx context.Context, in *Pod, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/service.PacketsReceiver/Ready", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PacketsReceiverServer is the server API for PacketsReceiver service.
// All implementations must embed UnimplementedPacketsReceiverServer
// for forward compatibility
type PacketsReceiverServer interface {
	AddPacket(PacketsReceiver_AddPacketServer) error
	Ready(context.Context, *Pod) (*Empty, error)
	mustEmbedUnimplementedPacketsReceiverServer()
}

// UnimplementedPacketsReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedPacketsReceiverServer struct {
}

func (UnimplementedPacketsReceiverServer) AddPacket(PacketsReceiver_AddPacketServer) error {
	return status.Errorf(codes.Unimplemented, "method AddPacket not implemented")
}
func (UnimplementedPacketsReceiverServer) Ready(context.Context, *Pod) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedPacketsReceiverServer) mustEmbedUnimplementedPacketsReceiverServer() {}

// UnsafePacketsReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PacketsReceiverServer will
// result in compilation errors.
type UnsafePacketsReceiverServer interface {
	mustEmbedUnimplementedPacketsReceiverServer()
}

func RegisterPacketsReceiverServer(s grpc.ServiceRegistrar, srv PacketsReceiverServer) {
	s.RegisterService(&PacketsReceiver_ServiceDesc, srv)
}

func _PacketsReceiver_AddPacket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PacketsReceiverServer).AddPacket(&packetsReceiverAddPacketServer{stream})
}

type PacketsReceiver_AddPacketServer interface {
	Send(*Empty) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type packetsReceiverAddPacketServer struct {
	grpc.ServerStream
}

func (x *packetsReceiverAddPacketServer) Send(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *packetsReceiverAddPacketServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PacketsReceiver_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacketsReceiverServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.PacketsReceiver/Ready",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacketsReceiverServer).Ready(ctx, req.(*Pod))
	}
	return interceptor(ctx, in, info, handler)
}

// PacketsReceiver_ServiceDesc is the grpc.ServiceDesc for PacketsReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PacketsReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.PacketsReceiver",
	HandlerType: (*PacketsReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ready",
			Handler:    _PacketsReceiver_Ready_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddPacket",
			Handler:       _PacketsReceiver_AddPacket_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "capture/capture.proto",
}

// PackgetGetterClient is the client API for PackgetGetter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PackgetGetterClient interface {
	GetPackets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PackgetGetter_GetPacketsClient, error)
}

type packgetGetterClient struct {
	cc grpc.ClientConnInterface
}

func NewPackgetGetterClient(cc grpc.ClientConnInterface) PackgetGetterClient {
	return &packgetGetterClient{cc}
}

func (c *packgetGetterClient) GetPackets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PackgetGetter_GetPacketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PackgetGetter_ServiceDesc.Streams[0], "/service.PackgetGetter/GetPackets", opts...)
	if err != nil {
		return nil, err
	}
	x := &packgetGetterGetPacketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PackgetGetter_GetPacketsClient interface {
	Recv() (*Packet, error)
	grpc.ClientStream
}

type packgetGetterGetPacketsClient struct {
	grpc.ClientStream
}

func (x *packgetGetterGetPacketsClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PackgetGetterServer is the server API for PackgetGetter service.
// All implementations must embed UnimplementedPackgetGetterServer
// for forward compatibility
type PackgetGetterServer interface {
	GetPackets(*Empty, PackgetGetter_GetPacketsServer) error
	mustEmbedUnimplementedPackgetGetterServer()
}

// UnimplementedPackgetGetterServer must be embedded to have forward compatible implementations.
type UnimplementedPackgetGetterServer struct {
}

func (UnimplementedPackgetGetterServer) GetPackets(*Empty, PackgetGetter_GetPacketsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPackets not implemented")
}
func (UnimplementedPackgetGetterServer) mustEmbedUnimplementedPackgetGetterServer() {}

// UnsafePackgetGetterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackgetGetterServer will
// result in compilation errors.
type UnsafePackgetGetterServer interface {
	mustEmbedUnimplementedPackgetGetterServer()
}

func RegisterPackgetGetterServer(s grpc.ServiceRegistrar, srv PackgetGetterServer) {
	s.RegisterService(&PackgetGetter_ServiceDesc, srv)
}

func _PackgetGetter_GetPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackgetGetterServer).GetPackets(m, &packgetGetterGetPacketsServer{stream})
}

type PackgetGetter_GetPacketsServer interface {
	Send(*Packet) error
	grpc.ServerStream
}

type packgetGetterGetPacketsServer struct {
	grpc.ServerStream
}

func (x *packgetGetterGetPacketsServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

// PackgetGetter_ServiceDesc is the grpc.ServiceDesc for PackgetGetter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackgetGetter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.PackgetGetter",
	HandlerType: (*PackgetGetterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPackets",
			Handler:       _PackgetGetter_GetPackets_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "capture/capture.proto",
}
