name: "e2e"
on:
  push:
    branches:
      - main
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - "mona/octocat"
      - "releases/**"
jobs:
  kind:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind: [v0.17.0, v0.14.0, v0.12.0] # Respectivly kubernetes 1.25, 1.24, 1.23
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"
      - name: Checkout
        uses: actions/checkout@v3
      - run: sudo apt update -y && sudo apt-get install -y libpcap-dev
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: ${{ matrix.kind }}
        env:
          KUBECONFIG: /tmp/kubeconfig
      - name: Testing
        env:
          KUBECONFIG: /tmp/kubeconfig
          KUBERNETES_MASTER: /tmp/kubeconfig
        run: |
          kubectl get nodes
          kubectl create deployment nginx --image=nginx
          kubectl wait deployment/nginx --for condition=Available=True --timeout=90s
          kubectl config set-context --current --namespace=default
      - run: |
          go test ./e2e/...
        env:
          KUBECONFIG: /tmp/kubeconfig
          KUBERNETES_MASTER: /tmp/kubeconfig
